on:
    push:
        tags:
            - 'v*'

jobs:
    gh_tagged_release:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            -   name: Set up dotnet
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: '7.0.401'
                    include-prerelease: false
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Build
                run: dotnet build src/SimpleLevelEditor.sln -c Release
            -   name: Test
                run: dotnet test src/SimpleLevelEditor.sln -c Release --no-build
            -   name: Create release
                id: create_release
                uses: actions/create-release@latest
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ github.ref }}
                    release_name: Release ${{ github.ref }}
                    draft: true
                    prerelease: true
