on:
    push:
        tags:
            - 'v*'

jobs:
    gh_tagged_release:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            -   name: Set up dotnet
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: '8.0.100'
                    include-prerelease: false
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Build and test
                run: dotnet test src/SimpleLevelEditor.sln -c Release
            -   name: Build optimized release
                run: >
                    dotnet publish src/SimpleLevelEditor/SimpleLevelEditor.csproj
                    -p:PublishTrimmed=True
                    -p:EnableCompressionInSingleFile=True
                    -p:PublishReadyToRun=False
                    -p:PublishProtocol=FileSystem
                    -p:TargetFramework=net7.0
                    -p:RuntimeIdentifier=win-x64
                    -p:Platform=x64
                    -p:Configuration=Release
                    -p:PublishDir=release-win-x64
                    -p:PublishSingleFile=True
                    -p:SelfContained=True
                    -p:PublishMethod=SELF_CONTAINED
                    -p:OutputType=WinExe
            -   name: Install zip
                uses: montudor/action-zip@v1
            -   name: Zip output
                run: zip -qq -r simple-level-editor-win-x64.zip release-win-x64
                working-directory: src/SimpleLevelEditor
            -   name: Create release
                id: create_release
                uses: marvinpinto/action-automatic-releases@latest
                with:
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    prerelease: true
                    files: src/SimpleLevelEditor/simple-level-editor-win-x64.zip
